using DataView2.Core.Models.LCMS_Data_Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace DataView2.Core.Helper
{
    public class DataViewSchemaQueries
    {
        public static List<KeyValuePair<string, string>> SchemaQueries = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string> ("Boundaries","INSERT INTO Boundaries (SurveyId, SurveyName, Coordinates, BoundariesMode) VALUES('', '', '', '');"),
                new KeyValuePair<string, string> ("CrackClassificationNodes","INSERT INTO CrackClassificationNodes (SurveyId, SegmentId, CrackId, X, Y, Width, 'Depth') VALUES('', 0, 0, 0, 0, 0, 0);"),
                new KeyValuePair<string, string> ("CrackClassifications","INSERT INTO CrackClassifications (SurveyId, SegmentId, CrackId, 'Length', WeightedDepth, WeightedWidth) VALUES('', 0, 0, 0, 0, 0);"),
                new KeyValuePair<string, string> ("GPS_Processed","INSERT INTO GPS_Processed (Chainage, Speed, LRPNum, GPSTime, Latitude, Longitude, Northing, Easting, AltitudeHAE, AltitudeMSL, Heading, PDOP, HDOP, GPSSource) VALUES(0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '');"),
                new KeyValuePair<string, string> ("LCMS_Bleeding","INSERT INTO LCMS_Bleeding (SurveyId, SurveyDate, ChainageStart, ChainageEnd, LRPNumStart, LRPChainageStart, LRPNumEnd, LRPChainageEnd, BleedingId, LeftBleedingIndex, LeftSeverity, RightBleedingIndex, RightSeverity, ImageFileIndex, PavementType, GPSLatitude, GPSLongitude, GPSAltitude, GeoJSON, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, 0, 0, 0, 0, 0, '', 0, '', '', '', 0, 0, 0, '', 0, 0, 0);"),
                new KeyValuePair<string, string> ("LCMS_Geometry_Processed","INSERT INTO LCMS_Geometry_Processed (Acc_X, Acc_Y, Acc_Z, Chainage, Count, CrossSlope, GPSAltitude, GPSLatitude, GPSLongitude, GPSTrackAngle, GeoJSON, Gyr_X, Gyr_Y, Gyr_Z, PavementType, Pitch, RadiusOfCurvature, Roll, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId, Slope, StatesOfCrossSlope, StatesOfSlope, Status, SurveyDate, SurveyId, Time, \"Timestamp\", Vel_X, Vel_Y, Vel_Z, Yaw) VALUES(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', 0, 0, 0, 0, 0, 0);"),
                new KeyValuePair<string, string> ("LCMS_Concrete_Joints","INSERT INTO LCMS_Concrete_Joints (SurveyId, SurveyDate, Chainage, LRPNumStart, LRPChainageStart, PavementType, JointId, JointDirection, Length_mm, AvgWidth_mm, AvgDepth_mm, FaultingAvgHeight_mm, FaultingMaxHeight_mm, FaultingMinHeight_mm, BadSealLength_mm, BadSealAvgDepth_mm, BadSealMaxDepth_mm, SpallingLength_mm, SpallingAvgDepth_mm, SpallingMaxDepth_mm, SpallingAvgWidth_mm, SpallingMaxWidth_mm, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, EndGPSLatitude, EndGPSLongitude, EndGPSAltitude, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0.0);"),
                new KeyValuePair<string, string> ("LCMS_Corner_Break","INSERT INTO LCMS_Corner_Break (SurveyId, SurveyDate, Chainage, LRPNumStart, LRPChainageStart, PavementType, CornerId, QuarterId, AvgDepth_mm, Area_mm2, BreakArea_mm2, CNR_SpallingArea_mm2, AreaRatio, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '', 0, 0, 0, 0, 0.0);"),
                new KeyValuePair<string, string> ("LCMS_Cracking_Raw","INSERT INTO LCMS_Cracking_Raw (SurveyId, SurveyDate, Chainage, LRPNumStart, LRPChainageStart, PavementType, CrackId, NodeId, NodeLength_mm, NodeWidth_mm, NodeDepth_mm, Severity, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', 0, 0, 0, 0, 0, '', '', 0, 0, '', 0, 0, 0, 0, 0, 0.0);"),
                new KeyValuePair<string, string> ("LCMS_Patch_Processed","INSERT INTO LCMS_Patch_Processed (SurveyId, SurveyDate, Chainage, LRPNumStart, LRPChainage, PavementType, PatchId, Length_mm, Width_mm, Area_m2, Severity, ConfidenceLevel, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', 0, 0, 0, 0, '', 0, '', 0, 0, 0, '', 0, 0, 0, 0, 0.0);"),
                new KeyValuePair<string, string> ("LCMS_PickOuts_Raw","INSERT INTO LCMS_PickOuts_Raw (SurveyId, SurveyDate, Chainage, LRPNumStart, LRPChainageStart, PavementType, PickOutId, Area_mm2, MaxDepth_mm, AvgDepth_mm, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', 0, 0, 0, 0, '', 0, 0, 0, '', 0, 0, 0, 0, 0.0);"),
                new KeyValuePair<string, string> ("LCMS_Potholes_Processed","INSERT INTO LCMS_Potholes_Processed (SurveyId, SurveyDate, Chainage, LRPNumStart, LRPChainage, PavementType, PotholeId, Area_mm2, MaxDepth_mm, AvgDepth_mm, MajorDiameter_mm, MinorDiameter_mm, AvgIntensity, Severity, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, '', 0, 0, 0, 0, 0.0);"),
                new KeyValuePair<string, string> ("LCMS_Ravelling_Raw","INSERT INTO LCMS_Ravelling_Raw (SurveyId, SurveyDate, Chainage, LRPNumStart, LRPChainageStart, PavementType, SquareId, SquareArea_mm2, Algorithm, ALG1_RavellingIndex, ALG1_RPI, ALG1_AVC, ALG2_RI_Percent, RI_AREA_mm2, Severity, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, '', 0, 0, 0, 0, 0.0);"),
                new KeyValuePair<string, string> ("LCMS_Rut_Processed","INSERT INTO LCMS_Rut_Processed (SurveyId, SurveyDate, Chainage, LRPNumber, LRPChainage, LeftDepth, LeftWidth, LeftCrossSection, LeftType, RightDepth, RightWidth, RightCrossSection, RightType, ImageFileIndex, GeoJSON, GPSLatitude, GPSLongitude, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0);"),
                new KeyValuePair<string, string> ("LCMS_Segment","INSERT INTO LCMS_Segment (SurveyId, SectionId, ImageFilePath, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, PavementType, GeoJSON, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId, Width, Height, PCI, Paser, AverageMPD_mm, AverageMTD_mm, BleedingSeverity, BleedingTotalArea_m2, BumpsTotalArea_m2, CrackClassificationTotalAreaFatigueCracks_m2, CrackClassificationTotalLengthLongCracks_mm, CrackClassificationTotalLengthOtherCracks_mm, CrackClassificationTotalLengthTransCracks_mm, CrackingTotalLengthAllNodes_mm, CrackingTotalLengthHighSevNodes_mm, CrackingTotalLengthLowSevNodes_mm, CrackingTotalLengthMedSevNodes_mm, GeometryAvgCrossSlope, GeometryAvgGradient, GeometryAvgHorizontalCurvature, GeometryAvgVerticalCurvature, IRIAverage, MmoCount, PatchesArea_m2, PickoutAvgPer_m2, PickoutCount, PotholesCount, PumpingArea_m2, RavellingSeverity, RavellingTotalArea_m2, RutAverage, SagsTotalArea_m2, SealedCrackTotalLength_mm, ShoveTotalLength_mm) VALUES('', '', '', 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);"),
                new KeyValuePair<string, string> ("LCMS_Spalling_Raw","INSERT INTO LCMS_Spalling_Raw (SurveyId, SurveyDate, Chainage, LRPNumber, LRPChainage, PavementType, JointId,JointDirection, SpallingId, AvgDepth_mm, AvgWidth_mm, Length_mm, ImageFileIndex, GPSLatitude, GPSLongitude, GPSAltitude, GPSTrackAngle, GeoJSON, QCAccepted, RoundedGPSLatitude, RoundedGPSLongitude, SegmentId) VALUES('', '', 0, 0, 0, '', 0, 0, 0, 0, 0, '', 0, 0, 0, '', 0, 0, 0, 0, '', 0.0);"),
                new KeyValuePair<string, string> ("SummaryCrackClasifications","INSERT INTO SummaryCrackClasifications (Chstart, Chend, LaneWidth, SampleArea, LongCrackLOW, LongCrackMED, LongCrackHIGH, TransCrackLOW, TransCrackMED, TransCrackHIGH, AlligatorCrackLOW, AlligatorCrackMED, AlligatorCrackHIGH, OtherCrackLOW, OtherCrackMED, OtherCrackHIGH, LongitudinalCracking, TransverseCracking, crackingWheelpaths, WheelpathsArea, FatigueArea, XmlFileName) VALUES(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');"),
                new KeyValuePair<string, string> ("TableExport","INSERT INTO TableExport (Name, File) VALUES('', '');"),
                new KeyValuePair<string, string> ("XMLObject","INSERT INTO XMLObject (Name, Parent, 'Type', 'Level', GeoJSON, GPSLatitude, GPSLongitude, RoundedGPSLatitude, RoundedGPSLongitude, SurveyId, SegmentId) VALUES('', '', '', 0, '', 0, 0, 0, 0, '', 0);")
            };

        public static string GetQueryStringByTableName(string tableName)
        {
            return SchemaQueries.FirstOrDefault(s => s.Key.Equals(tableName)).Value.Split("VALUES")[0].Trim() + " VALUES ";
        }

    }
}