// <auto-generated />
using System;
using DataView2.GrpcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataView2.GrpcService.Migrations.Metadata
{
    [DbContext(typeof(AppDbContextMetadata))]
    [Migration("20240218212552_AddedIndexOfSurveyIdAndSegId")]
    partial class AddedIndexOfSurveyIdAndSegId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("DataView2.Core.Models.DatabaseRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseRegistry");
                });

            modelBuilder.Entity("DataView2.Core.Models.Database_Tables.ProjectRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectRegistries");
                });

            modelBuilder.Entity("DataView2.Core.Models.GeneralSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "NetWorking",
                            Description = "DataView IP Address",
                            GPSLatitude = 0.0,
                            GPSLongitude = 0.0,
                            GeoJSON = "DefaultGeoJSON",
                            Name = "IP Address",
                            RoundedGPSLatitude = 0.0,
                            RoundedGPSLongitude = 0.0,
                            Type = 1,
                            Value = "0.0.0.1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Path",
                            Description = "Offline Map Path",
                            GPSLatitude = 0.0,
                            GPSLongitude = 0.0,
                            GeoJSON = "DefaultGeoJSON",
                            Name = "Offline Map Path",
                            RoundedGPSLatitude = 0.0,
                            RoundedGPSLongitude = 0.0,
                            Type = 2,
                            Value = "D:\\Khushbu_Badheka\\Dataview3\\DataView2\\DataView2.GrpcService\\offlineMap.vtpk"
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Setting.CrackClassificationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreOutLanes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSizeToAvoidMerge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSizeToStraight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumDeep")
                        .HasColumnType("REAL");

                    b.Property<double>("Straightness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CrackClassification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IgnoreOutLanes = true,
                            MinSizeToAvoidMerge = 6,
                            MinSizeToStraight = 4,
                            MinimumDeep = 0.0,
                            Straightness = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.TablesSetting", b =>
                {
                    b.Property<int>("RootPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RootPage");

                    b.ToTable((string)null);

                    b.ToView("NoTable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
