// <auto-generated />
using System;
using DataView2.GrpcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataView2.GrpcService.Migrations.Metadata
{
    [DbContext(typeof(AppDbContextMetadata))]
    [Migration("20240328011333_AddedMapGraphic")]
    partial class AddedMapGraphic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("DataView2.Core.Models.DatabaseRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseRegistry");
                });

            modelBuilder.Entity("DataView2.Core.Models.Database_Tables.ProjectRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectRegistries");
                });

            modelBuilder.Entity("DataView2.Core.Models.GeneralSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "NetWorking",
                            Description = "DataView IP Address",
                            GPSLatitude = 0.0,
                            GPSLongitude = 0.0,
                            GeoJSON = "DefaultGeoJSON",
                            Name = "IP Address",
                            RoundedGPSLatitude = 0.0,
                            RoundedGPSLongitude = 0.0,
                            Type = 1,
                            Value = "0.0.0.1"
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Other.MapGraphicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alpha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Green")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Red")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MapGraphic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alpha = 255,
                            Blue = 255,
                            Green = 255,
                            Name = "CrackingRaw0",
                            Red = 64,
                            SymbolType = "Line",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Alpha = 255,
                            Blue = 0,
                            Green = 192,
                            Name = "CrackingRaw1",
                            Red = 0,
                            SymbolType = "Line",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Alpha = 255,
                            Blue = 15,
                            Green = 151,
                            Name = "CrackingRaw2",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 4,
                            Alpha = 255,
                            Blue = 0,
                            Green = 0,
                            Name = "CrackingRaw3",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 5,
                            Alpha = 170,
                            Blue = 207,
                            Green = 159,
                            Name = "RavellingRaw1",
                            Red = 46,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Alpha = 170,
                            Blue = 176,
                            Green = 105,
                            Name = "RavellingRaw2",
                            Red = 53,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 7,
                            Alpha = 170,
                            Blue = 83,
                            Green = 0,
                            Name = "RavellingRaw3",
                            Red = 191,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Alpha = 170,
                            Blue = 35,
                            Green = 26,
                            Name = "PickOutRaw",
                            Red = 168,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 9,
                            Alpha = 170,
                            Blue = 110,
                            Green = 70,
                            Name = "PotholesProcessed",
                            Red = 44,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 10,
                            Alpha = 170,
                            Blue = 150,
                            Green = 50,
                            Name = "PatchProcessed",
                            Red = 150,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 11,
                            Alpha = 170,
                            Blue = 0,
                            Green = 255,
                            Name = "SpallingRaw",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 12,
                            Alpha = 170,
                            Blue = 0,
                            Green = 88,
                            Name = "CornerBreak",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 13,
                            Alpha = 255,
                            Blue = 225,
                            Green = 105,
                            Name = "ConcreteJoint",
                            Red = 65,
                            SymbolType = "Line",
                            Thickness = 1.0
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Setting.CrackClassificationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreOutLanes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSizeToAvoidMerge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSizeToStraight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumDeep")
                        .HasColumnType("REAL");

                    b.Property<double>("Straightness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CrackClassification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IgnoreOutLanes = true,
                            MinSizeToAvoidMerge = 6,
                            MinSizeToStraight = 4,
                            MinimumDeep = 0.0,
                            Straightness = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.TablesSetting", b =>
                {
                    b.Property<int>("RootPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RootPage");

                    b.ToTable((string)null);

                    b.ToView("NoTable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
