// <auto-generated />
using System;
using DataView2.GrpcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataView2.GrpcService.Migrations.Metadata
{
    [DbContext(typeof(AppDbContextMetadata))]
    [Migration("20241030202800_addedIconSize")]
    partial class addedIconSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DataView2.Core.Models.DatabaseRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseRegistry");
                });

            modelBuilder.Entity("DataView2.Core.Models.Database_Tables.ProjectRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectRegistries");
                });

            modelBuilder.Entity("DataView2.Core.Models.DatasetBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("DataView2.Core.Models.GeneralSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "NetWorking",
                            Description = "DataView IP Address",
                            GPSLatitude = 0.0,
                            GPSLongitude = 0.0,
                            GeoJSON = "DefaultGeoJSON",
                            Name = "IP Address",
                            RoundedGPSLatitude = 0.0,
                            RoundedGPSLongitude = 0.0,
                            Type = 1,
                            Value = "0.0.0.1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Networking",
                            Description = "URL for exporting",
                            GPSLatitude = 0.0,
                            GPSLongitude = 0.0,
                            GeoJSON = "DefaultGeoJSON",
                            Name = "ExportURL",
                            RoundedGPSLatitude = 0.0,
                            RoundedGPSLongitude = 0.0,
                            Type = 2,
                            Value = "https://dvwebservice20240808112104.azurewebsites.net"
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Other.ColorCodeInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAboveFrom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStringProperty")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxRange")
                        .HasColumnType("REAL");

                    b.Property<double>("MinRange")
                        .HasColumnType("REAL");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StringProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ColorCodeInformation");
                });

            modelBuilder.Entity("DataView2.Core.Models.Other.MapGraphicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alpha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Green")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Red")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MapGraphic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alpha = 255,
                            Blue = 255,
                            Green = 255,
                            Name = "Cracking0",
                            Red = 64,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 2,
                            Alpha = 255,
                            Blue = 0,
                            Green = 192,
                            Name = "Cracking1",
                            Red = 0,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 3,
                            Alpha = 255,
                            Blue = 15,
                            Green = 151,
                            Name = "Cracking2",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 4,
                            Alpha = 255,
                            Blue = 0,
                            Green = 0,
                            Name = "Cracking3",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 5,
                            Alpha = 170,
                            Blue = 207,
                            Green = 159,
                            Name = "Ravelling1",
                            Red = 46,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Alpha = 170,
                            Blue = 176,
                            Green = 105,
                            Name = "Ravelling2",
                            Red = 53,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 7,
                            Alpha = 170,
                            Blue = 83,
                            Green = 0,
                            Name = "Ravelling3",
                            Red = 191,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Alpha = 170,
                            Blue = 35,
                            Green = 26,
                            Name = "Pickout",
                            Red = 168,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 9,
                            Alpha = 170,
                            Blue = 110,
                            Green = 70,
                            Name = "Potholes",
                            Red = 44,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 10,
                            Alpha = 170,
                            Blue = 150,
                            Green = 50,
                            Name = "Patch",
                            Red = 150,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 11,
                            Alpha = 170,
                            Blue = 0,
                            Green = 255,
                            Name = "Spalling",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 12,
                            Alpha = 170,
                            Blue = 0,
                            Green = 88,
                            Name = "Corner Break",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 13,
                            Alpha = 255,
                            Blue = 225,
                            Green = 105,
                            Name = "Concrete Joint",
                            Red = 65,
                            SymbolType = "Line",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 14,
                            Alpha = 255,
                            Blue = 255,
                            Green = 0,
                            Name = "Boundaries",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 15,
                            Alpha = 50,
                            Blue = 0,
                            Green = 0,
                            Name = "Segment",
                            Red = 0,
                            SymbolType = "Segment",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 16,
                            Alpha = 255,
                            Blue = 255,
                            Green = 0,
                            Name = "HighlightedSegment",
                            Red = 191,
                            SymbolType = "Segment",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 17,
                            Alpha = 255,
                            Blue = 40,
                            Green = 253,
                            Name = "Dropoff",
                            Red = 0,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 18,
                            Alpha = 255,
                            Blue = 250,
                            Green = 125,
                            Name = "Curb",
                            Red = 225,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 19,
                            Alpha = 170,
                            Blue = 0,
                            Green = 255,
                            Name = "Marking Contour",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 20,
                            Alpha = 255,
                            Blue = 83,
                            Green = 22,
                            Name = "Sealed Crack",
                            Red = 191,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 21,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            Name = "Lwp IRI",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 22,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            Name = "Rwp IRI",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 23,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            Name = "Cwp IRI",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 24,
                            Alpha = 255,
                            Blue = 226,
                            Green = 43,
                            Name = "Lane IRI",
                            Red = 138,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 25,
                            Alpha = 170,
                            Blue = 0,
                            Green = 255,
                            Name = "Rutting",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 26,
                            Alpha = 255,
                            Blue = 17,
                            Green = 247,
                            Name = "MMO",
                            Red = 17,
                            SymbolType = "FillLine",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 27,
                            Alpha = 255,
                            Blue = 17,
                            Green = 247,
                            Name = "Pumping",
                            Red = 17,
                            SymbolType = "FillLine",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 28,
                            Alpha = 170,
                            Blue = 0,
                            Green = 0,
                            Name = "Shove",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 29,
                            Alpha = 255,
                            Blue = 0,
                            Green = 0,
                            Name = "Rumble Strip",
                            Red = 255,
                            SymbolType = "FillLine",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 30,
                            Alpha = 170,
                            Blue = 0,
                            Green = 255,
                            Name = "Bleeding1",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 31,
                            Alpha = 170,
                            Blue = 0,
                            Green = 165,
                            Name = "Bleeding2",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 32,
                            Alpha = 170,
                            Blue = 0,
                            Green = 0,
                            Name = "Bleeding3",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 33,
                            Alpha = 128,
                            Blue = 255,
                            Green = 128,
                            Name = "Macro Texture",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 34,
                            Alpha = 128,
                            Blue = 100,
                            Green = 50,
                            Name = "Geometry",
                            Red = 0,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 35,
                            Alpha = 128,
                            Blue = 0,
                            Green = 255,
                            Name = "Sags Bumps",
                            Red = 0,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 36,
                            Alpha = 128,
                            Blue = 255,
                            Green = 0,
                            Name = "Water Entrapment",
                            Red = 0,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 37,
                            Alpha = 170,
                            Blue = 35,
                            Green = 26,
                            Name = "LasPoint",
                            Red = 168,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Other.MetaTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Column1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column10Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column10Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column1Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column1Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column2Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column2Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column5Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column5Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column6Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column6Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column7Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column7Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column8Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column8Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column9")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column9Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column9Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IconSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MetaTable");
                });

            modelBuilder.Entity("DataView2.Core.Models.Setting.CrackClassificationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreOutLanes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSizeToAvoidMerge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSizeToStraight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumDeep")
                        .HasColumnType("REAL");

                    b.Property<double>("Straightness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CrackClassification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IgnoreOutLanes = true,
                            MinSizeToAvoidMerge = 6,
                            MinSizeToStraight = 4,
                            MinimumDeep = 0.0,
                            Straightness = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.TablesSetting", b =>
                {
                    b.Property<int>("RootPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RootPage");

                    b.ToTable((string)null);

                    b.ToView("NoTable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
