// <auto-generated />
using System;
using DataView2.GrpcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataView2.GrpcService.Migrations.Metadata
{
    [DbContext(typeof(AppDbContextMetadata))]
    [Migration("20250828224948_ChangeInGraphicAndColorCode")]
    partial class ChangeInGraphicAndColorCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DataView2.Core.Models.DatabaseRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseRegistry");
                });

            modelBuilder.Entity("DataView2.Core.Models.Database_Tables.ProjectRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdProject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtActionResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectRegistries");
                });

            modelBuilder.Entity("DataView2.Core.Models.DatasetBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("DataView2.Core.Models.GeneralSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinateSystemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoundedGPSLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RoundedGPSLongitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "NetWorking",
                            CoordinateSystemType = "",
                            Description = "DataView IP Address",
                            GPSLatitude = 0.0,
                            GPSLongitude = 0.0,
                            GeoJSON = "DefaultGeoJSON",
                            Name = "IP Address",
                            RoundedGPSLatitude = 0.0,
                            RoundedGPSLongitude = 0.0,
                            Type = 1,
                            Value = "0.0.0.1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Networking",
                            CoordinateSystemType = "",
                            Description = "URL for exporting",
                            GPSLatitude = 0.0,
                            GPSLongitude = 0.0,
                            GeoJSON = "DefaultGeoJSON",
                            Name = "ExportURL",
                            RoundedGPSLatitude = 0.0,
                            RoundedGPSLongitude = 0.0,
                            Type = 2,
                            Value = "https://dvwebservice20240808112104.azurewebsites.net"
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Other.ColorCodeInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAboveFrom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStringProperty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxRange")
                        .HasColumnType("REAL");

                    b.Property<double>("MinRange")
                        .HasColumnType("REAL");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StringProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ColorCodeInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HexColor = "#E17DFAFF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Type",
                            StringProperty = "Curb",
                            TableName = "Curb DropOff",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 2,
                            HexColor = "#00FD28FF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Type",
                            StringProperty = "Dropoff",
                            TableName = "Curb DropOff",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 3,
                            HexColor = "#40FFFFFF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Very Low",
                            TableName = "Cracking",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 4,
                            HexColor = "#00C000FF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Low",
                            TableName = "Cracking",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 5,
                            HexColor = "#FF970FFF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Medium",
                            TableName = "Cracking",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 6,
                            HexColor = "#FF0000FF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "High",
                            TableName = "Cracking",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 7,
                            HexColor = "#40FFFFFF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Very Low",
                            TableName = "Crack Summary",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 8,
                            HexColor = "#00C000FF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Low",
                            TableName = "Crack Summary",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 9,
                            HexColor = "#FF970FFF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Medium",
                            TableName = "Crack Summary",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 10,
                            HexColor = "#FF0000FF",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "High",
                            TableName = "Crack Summary",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 11,
                            HexColor = "#2E9FCFAA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Low",
                            TableName = "Ravelling",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 12,
                            HexColor = "#3569B0AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Medium",
                            TableName = "Ravelling",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 13,
                            HexColor = "#BF0053AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "High",
                            TableName = "Ravelling",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 14,
                            HexColor = "#FFFF00AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Low",
                            TableName = "Bleeding",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 15,
                            HexColor = "#FFA500AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Medium",
                            TableName = "Bleeding",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 16,
                            HexColor = "#FF0000AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "High",
                            TableName = "Bleeding",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 17,
                            HexColor = "#00FF00AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Very Low",
                            TableName = "Segment Grid",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 18,
                            HexColor = "#FFFF00AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Low",
                            TableName = "Segment Grid",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 19,
                            HexColor = "#FFA500AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Medium",
                            TableName = "Segment Grid",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 20,
                            HexColor = "#FF0000AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "High",
                            TableName = "Segment Grid",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 21,
                            HexColor = "#C80000AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "Very High",
                            TableName = "Segment Grid",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 22,
                            HexColor = "#000000AA",
                            IsAboveFrom = false,
                            IsStringProperty = true,
                            LabelProperty = "No Label",
                            MaxRange = 0.0,
                            MinRange = 0.0,
                            Property = "Severity",
                            StringProperty = "None",
                            TableName = "Segment Grid",
                            Thickness = 3.0
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Other.MapGraphicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alpha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Green")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Red")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MapGraphic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alpha = 255,
                            Blue = 255,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Cracking",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 2,
                            Alpha = 170,
                            Blue = 0,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Ravelling",
                            Red = 0,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Alpha = 170,
                            Blue = 35,
                            Green = 26,
                            LabelProperty = "No Label",
                            Name = "Pickout",
                            Red = 168,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 4,
                            Alpha = 170,
                            Blue = 110,
                            Green = 70,
                            LabelProperty = "No Label",
                            Name = "Potholes",
                            Red = 44,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 5,
                            Alpha = 170,
                            Blue = 150,
                            Green = 50,
                            LabelProperty = "No Label",
                            Name = "Patch",
                            Red = 150,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Alpha = 170,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Spalling",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 7,
                            Alpha = 170,
                            Blue = 0,
                            Green = 88,
                            LabelProperty = "No Label",
                            Name = "Corner Break",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Alpha = 255,
                            Blue = 225,
                            Green = 105,
                            LabelProperty = "No Label",
                            Name = "Concrete Joint",
                            Red = 65,
                            SymbolType = "Line",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 9,
                            Alpha = 255,
                            Blue = 255,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Boundaries",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 10,
                            Alpha = 50,
                            Blue = 0,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Segment",
                            Red = 0,
                            SymbolType = "Segment",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 11,
                            Alpha = 255,
                            Blue = 255,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "HighlightedSegment",
                            Red = 191,
                            SymbolType = "Segment",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 12,
                            Alpha = 255,
                            Blue = 0,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Curb DropOff",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 13,
                            Alpha = 170,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Marking Contour",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 14,
                            Alpha = 255,
                            Blue = 83,
                            Green = 22,
                            LabelProperty = "No Label",
                            Name = "Sealed Crack",
                            Red = 191,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 15,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Lwp IRI",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 16,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Rwp IRI",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 17,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Cwp IRI",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 18,
                            Alpha = 255,
                            Blue = 226,
                            Green = 43,
                            LabelProperty = "No Label",
                            Name = "Lane IRI",
                            Red = 138,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 19,
                            Alpha = 255,
                            Blue = 17,
                            Green = 247,
                            LabelProperty = "No Label",
                            Name = "MMO",
                            Red = 17,
                            SymbolType = "FillLine",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 20,
                            Alpha = 255,
                            Blue = 17,
                            Green = 247,
                            LabelProperty = "No Label",
                            Name = "Pumping",
                            Red = 17,
                            SymbolType = "FillLine",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 21,
                            Alpha = 170,
                            Blue = 0,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Shove",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 22,
                            Alpha = 255,
                            Blue = 0,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Rumble Strip",
                            Red = 255,
                            SymbolType = "FillLine",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 23,
                            Alpha = 170,
                            Blue = 255,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Bleeding",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 24,
                            Alpha = 128,
                            Blue = 255,
                            Green = 128,
                            LabelProperty = "No Label",
                            Name = "Macro Texture",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 25,
                            Alpha = 128,
                            Blue = 100,
                            Green = 50,
                            LabelProperty = "No Label",
                            Name = "Geometry",
                            Red = 0,
                            SymbolType = "Line",
                            Thickness = 3.0
                        },
                        new
                        {
                            Id = 26,
                            Alpha = 128,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Sags Bumps",
                            Red = 0,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 27,
                            Alpha = 128,
                            Blue = 255,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Water Entrapment",
                            Red = 0,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 28,
                            Alpha = 170,
                            Blue = 35,
                            Green = 26,
                            LabelProperty = "No Label",
                            Name = "LasPoint",
                            Red = 168,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 29,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Left Rut",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 30,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Right Rut",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 31,
                            Alpha = 255,
                            Blue = 0,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Lane Rut",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 5.0
                        },
                        new
                        {
                            Id = 32,
                            Alpha = 170,
                            Blue = 0,
                            Green = 0,
                            LabelProperty = "No Label",
                            Name = "Segment Grid",
                            Red = 0,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 33,
                            Alpha = 170,
                            Blue = 0,
                            Green = 165,
                            LabelProperty = "No Label",
                            Name = "LasPoints",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 34,
                            Alpha = 170,
                            Blue = 255,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Grooves",
                            Red = 255,
                            SymbolType = "Fill",
                            Thickness = 1.0
                        },
                        new
                        {
                            Id = 35,
                            Alpha = 255,
                            Blue = 255,
                            Green = 255,
                            LabelProperty = "No Label",
                            Name = "Crack Summary",
                            Red = 255,
                            SymbolType = "Line",
                            Thickness = 3.0
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.Other.MetaTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Column1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column10Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column10Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column11")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column11Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column11Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column12")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column12Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column12Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column13")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column13Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column13Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column14")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column14Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column14Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column15")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column15Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column15Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column16")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column16Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column16Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column17")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column17Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column17Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column18")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column18Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column18Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column19")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column19Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column19Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column1Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column1Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column20")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column20Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column20Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column21")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column21Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column21Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column22")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column22Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column22Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column23")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column23Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column23Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column24")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column24Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column24Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column25")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column25Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column25Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column2Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column2Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column5Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column5Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column6Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column6Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column7Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column7Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column8Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column8Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column9")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column9Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column9Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IconSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MetaTable");
                });

            modelBuilder.Entity("DataView2.Core.Models.Setting.CrackClassificationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HighThreshold")
                        .HasColumnType("REAL");

                    b.Property<bool>("IgnoreOutLanes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LowMediumThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("LowThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("MediumHighThreshold")
                        .HasColumnType("REAL");

                    b.Property<int>("MinSizeToAvoidMerge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSizeToStraight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumDeep")
                        .HasColumnType("REAL");

                    b.Property<double>("Straightness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CrackClassification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfigFilePath = "",
                            HighThreshold = 0.0,
                            IgnoreOutLanes = true,
                            LowMediumThreshold = 0.0,
                            LowThreshold = 0.0,
                            MediumHighThreshold = 0.0,
                            MinSizeToAvoidMerge = 6,
                            MinSizeToStraight = 4,
                            MinimumDeep = 0.0,
                            Straightness = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("DataView2.Core.Models.TablesSetting", b =>
                {
                    b.Property<int>("RootPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RootPage");

                    b.ToTable((string)null);

                    b.ToView("NoTable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
